name: Deploy

on:
  workflow_run:
    workflows: ["Run tests"]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_KEY}}
          heroku_app_name: "pgblogview"
          heroku_email: "gabrielsantanasilva85@gmail.com"
          usedocker: true
